version: "3.7"

services:
  web-server:
    build: ./api
    container_name: adway-api
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/nodemon.json:/usr/src/app/nodemon.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"
