version: "3.7"

services:
  ui:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - web-server
    volumes: 
      - ./client/src/:/usr/src/app/src
  web-server:
    build: ./api
    container_name: adway-api
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/nodemon.json:/usr/src/app/nodemon.json
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
